config/routes.rb
Rails.application.routes.draw do
  # Root is the unauthenticated path
  root 'sessions#unauth'

  # Sessions URL
  get 'sessions/unauth', as: :login
  post 'sessions/login', as: :signin
  delete 'sessions/logout', as: :logout

  # Resourceful routes for article
  resources :articles, only: [:show, :index]
  get '/get_articles', to: 'articles#refresh', as: 'scrape_article'
  get '/admin/scrape', to: 'articles#refresh'
  get '/interests', to: 'articles#my_interests', as: 'interests'
  # Resourceful routes for user
  resource :user, only: [:create, :new, :update, :destroy, :edit]
  get '/user/new', to: 'users#new', as: 'users'
  post '/user/new', to: 'users#create', as: 'users_new'
  get '/user/destroy', to: 'users#destroy', as: 'users_destroy'
  patch '/user', to: 'users#update', as: 'user_edit'
  get 'sessions/email', as: :email
  get '/admin/email', to: 'users#email', as: :email_admin
  get '/next_page', to: 'articles#next_page', as: 'next_page_route'
end

app/views/layouts/_nav_bar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">The Digest</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if current_user %>
        <ul class="nav navbar-nav">
          <li><%= link_to "Articles", articles_path %></li>
          <% if current_user.interest_list != [] %>
          <li><%= link_to "Interests", interests_path %></li>
          <% else %>
          <li><%= link_to "Please Add Interests", edit_user_path(current_user)%></li>
          <% end %>
        </ul>
        <div class="navbar-form navbar-right">
          <%= form_tag(articles_path, :method => "get", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Search Articles" %>
            <%= submit_tag "Search" %>
          <% end %>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to current_user.full_name, edit_user_path(current_user)%></li>
          <li><%= link_to "Log Out", logout_path, method: :delete%></li>
        </ul>
      <% end %>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Digest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render partial: '/layouts/nav_bar' %>
<div class="container">
  <%= yield %>
</div>

</body>
</html>